app = "event-feedback-hub"
primary_region = "iad"

[build]
dockerfile = "apps/server/Dockerfile"

[env]
PORT = "8080"
NODE_ENV = "production"

[[services]]
internal_port = 8080
protocol = "tcp"
processes = ["app"]

[services.concurrency]
type = "requests"
soft_limit = 25
hard_limit = 50

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = "10s"
timeout = "2s"
method = "GET"
path = "/health"
protocol = "http"
